OPENAI_MODEL = "gpt-5.4-mini"
MAX_TOPICS = None
SKIP_EXISTING_SCRIPTS = True
COPY_SCRIPT_TO_APPROVAL = True
VOICE_MODEL = "gpt-4o-mini-tts"
VOICE_NAME = "marin"
IMAGE_MODEL = "gpt-image-1"
IMAGE_SIZE = "1024x1536"
IMAGE_QUALITY = "medium"
IMAGE_STYLE = "clean modern editorial illustration, educational explainer style, simplified shapes, soft lighting, subtle depth, balanced composition, calm professional look, minimal background, no photorealism, no comic-book action effects, no exaggerated motion lines, no glowing explosions, no readable text, no logos, vertical 9:16"
FORCE_REGENERATE_SCENES = False
FORCE_REGENERATE_VIDEO = False
